//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diseño.BaseD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingresoVehiculo
    {
        public int NumTicket { get; set; }
        public string tipoVhlo { get; set; }
        public string Placa { get; set; }
        public string NumCascos { get; set; }
        public int CuposDis { get; set; }
        public DateTime Fecha { get; set; }
        public TimeSpan hora { get; set; }
    }
}
