//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diseño.BaseD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAlidaVehiculos
    {
        public int NumTicket { get; set; }
        public string tipoVhlo { get; set; }
        public string Placa { get; set; }
        public string NumCascos { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.TimeSpan> HoraIngreso { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<System.TimeSpan> HoraSalida { get; set; }
        public Nullable<decimal> Pago { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> Cambio { get; set; }
    }
}
