//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diseño.BaseD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tari
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> HoraEstacioMoto { get; set; }
        public Nullable<decimal> DiaEstacioMoto { get; set; }
        public Nullable<decimal> SemanaEstacioMoto { get; set; }
        public Nullable<decimal> QuincenaEstacioMoto { get; set; }
        public Nullable<decimal> MensualidadEstacioMoto { get; set; }
        public Nullable<decimal> HoraEstacioBici { get; set; }
        public Nullable<decimal> DiaEstacioBici { get; set; }
        public Nullable<decimal> SemanaEstacioBici { get; set; }
        public Nullable<decimal> QuincenaEstacioBici { get; set; }
        public Nullable<decimal> MensualidadEstacioBici { get; set; }
        public Nullable<int> CuposDIsponibles { get; set; }
    }
}
